### ISSUE TITLE
Add a makefile

### ISSUE THREAD

**Issue by DelusionalOptimist** [Shreyas220/loadbalancer#6]
### Context?
A [makefile](https://opensource.com/article/18/8/what-how-makefile) is used to automate steps involved in build process. It has various targets which specify which behave like functions and can be called like `make <target-name`

### What has to be done?
Add some make targets which will help us build the binary, docker image etc. Some useful ones:
- build: compiles the binary
- docker-build: builds the docker image
- run: runs the server locally
- run-compose: runs the server in a container using docker compose

### Simple examples
* [Compile binary and run it locally](https://github.com/DelusionalOptimist/distance-api/blob/ce434c7cc06f1117ee0af4c1984a0842b0820ac3/Makefile#L5)
* [Compile docker image](https://github.com/DelusionalOptimist/distance-api/blob/ce434c7cc06f1117ee0af4c1984a0842b0820ac3/Makefile#L9)

**Comment by rexagod** [comment]
_stares_

**Comment by DelusionalOptimist** [comment]
_bans rexagod_

**Comment by exitflynn** [comment]
_stairs 📶_

**Comment by rexagod** [comment]
Big brain.

**Comment by exitflynn** [comment]
🅱️anks 🅱️ane
😎

**Comment by DelusionalOptimist** [comment]
Assigned both of you. Have fun collaborating! :people_hugging:

**Comment by exitflynn** [comment]
jus like ol times :b: 😎

ty mr @DelusionalOptimist

**Comment by exitflynn** [comment]
(also ayo @rexagod no ⚔️ snatchin⚔️ rn, i gotta visit fam today, we clear? 🔫😠)

**Comment by rexagod** [comment]
Sure, trust me :b:ane.

![image](https://user-images.githubusercontent.com/33557095/193934246-3f33d57e-d32a-400f-8aaf-a6b6e7dc1d1c.png)

**Comment by rexagod** [comment]
@exitflynn My :b:ad dawg, I slipped and fell, and accidentally created sent a PR.

**Comment by rexagod** [comment]
I sleep.
